### ISSUE TITLE
NameError: name 'RegistrationBlock' is not defined

### ISSUE THREAD

**Issue by xuzhuoyue** [chanchanchan97/ICAFusion#3]
Traceback (most recent call last):
  File "train.py", line 588, in <module>
    train_rgb_ir(hyp, opt, device, tb_writer)
  File "train.py", line 92, in train_rgb_ir
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/root/ICAFusion-main/models/yolo_test.py", line 96, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/root/ICAFusion-main/models/yolo_test.py", line 302, in parse_model
    elif m in [TransformerFusionBlock, RegistrationBlock, STNFusionBlock]:
NameError: name 'RegistrationBlock' is not defined

**Comment by xuzhuoyue** [comment]
May I ask why name 'RegistrationBlock' is not defined appears?

**Comment by chanchanchan97** [comment]
You can delete it  in "elif m in [TransformerFusionBlock, RegistrationBlock, STNFusionBlock]:". I may not define this function in common.py.

**Comment by Kai-C-Kaslana** [comment]
Traceback (most recent call last):
  File "train.py", line 588, in <module>
    train_rgb_ir(hyp, opt, device, tb_writer)
  File "train.py", line 92, in train_rgb_ir
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/amax/home/chenzhaokai/ICAFusion/models/yolo_test.py", line 96, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/amax/home/chenzhaokai/ICAFusion/models/yolo_test.py", line 308, in parse_model
    c2 = ch[f]
TypeError: list indices must be integers or slices, not list
Exercuse me, after deleting "elif m in [TransformerFusionBlock, RegistrationBlock, STNFusionBlock]:",the new error appears as mentioned above. I tried to use "ch=ch[f[0]]" to replace "c2 = ch[f]" but it didn't work. 
so I would like to ask how to fix that error?

**Comment by chanchanchan97** [comment]
Sorry, you just delete the list element 'RegistrationBlock' in "elif m in [TransformerFusionBlock, RegistrationBlock, STNFusionBlock]:". 
The modified code should be "elif m in [TransformerFusionBlock, TNFusionBlock]:".

**Comment by ztyzt** [comment]
> May I ask why name 'RegistrationBlock' is not defined appears?

你好，请问我可以向你请教这个项目有关运行准备方面的问题吗？（比如一些参数还有路径的配置问题）

**Comment by ztyzt** [comment]
> May I ask why name 'RegistrationBlock' is not defined appears?

你好，请问我可以向你请教这个项目有关运行准备方面的问题吗？（比如一些参数还有路径的配置问题）

**Comment by zhangxin253675** [comment]
您好！我将RegistrationBlock删除了，之后报错：Traceback (most recent call last):
  File "/home/zx/PycharmProjects/det_fuxian/ICAFusion-main/train.py", line 588, in <module>
    train_rgb_ir(hyp, opt, device, tb_writer)
  File "/home/zx/PycharmProjects/det_fuxian/ICAFusion-main/train.py", line 92, in train_rgb_ir
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/zx/PycharmProjects/det_fuxian/ICAFusion-main/models/yolo_test.py", line 96, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/home/zx/PycharmProjects/det_fuxian/ICAFusion-main/models/yolo_test.py", line 305, in parse_model
    elif m in [TransformerFusionBlock, STNFusionBlock]:
NameError: name 'STNFusionBlock' is not defined

**Comment by honor-ai** [comment]
您好！我将RegistrationBlock和STNFusionBlock都删除了，之后报错：
Traceback (most recent call last):
  File "/projects/ICAFusion-main/train.py", line 588, in <module>
    train_rgb_ir(hyp, opt, device, tb_writer)
  File "/projects/ICAFusion-main/train.py", line 102, in train_rgb_ir
    model = Model(opt.cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/projects/ICAFusion-main/models/yolo_test.py", line 96, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/projects/ICAFusion-main/models/yolo_test.py", line 302, in parse_model
    elif m in TransformerFusionBlock:
TypeError: argument of type 'type' is not iterable
