### ISSUE TITLE
RuntimeError: stride should not be zero

### ISSUE THREAD

**Issue by chenyao1216** [chanchanchan97/ICAFusion#31]
Traceback (most recent call last):
  File "train.py", line 590, in <module>
    train_rgb_ir(hyp, opt, device, tb_writer)
  File "train.py", line 381, in train_rgb_ir
    results, maps, MRresult, times = test.test(data_dict,
  File "/data/zcy/ICAFusion-main/test.py", line 128, in test
    out, _, train_out = model(img_rgb, img_ir, augment=augment)  # inference and training outputs
  File "/data/zcy/anaconda3/envs/ica/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zcy/ICAFusion-main/models/yolo_test.py", line 133, in forward
    return self.forward_once(x, x2, profile)  # single-scale inference, train
  File "/data/zcy/ICAFusion-main/models/yolo_test.py", line 157, in forward_once
    x = m(x)  # run
  File "/data/zcy/anaconda3/envs/ica/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zcy/ICAFusion-main/models/common.py", line 817, in forward
    new_rgb_fea = self.vis_coefficient(self.avgpool(rgb_fea), self.maxpool(rgb_fea))
  File "/data/zcy/anaconda3/envs/ica/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zcy/ICAFusion-main/models/common.py", line 885, in forward
    y = nn.AvgPool2d(kernel_size=self.kernel_size, stride=(self.stride_h, self.stride_w), padding=0)(x)
  File "/data/zcy/anaconda3/envs/ica/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zcy/anaconda3/envs/ica/lib/python3.8/site-packages/torch/nn/modules/pooling.py", line 615, in forward
    return F.avg_pool2d(input, self.kernel_size, self.stride,
RuntimeError: stride should not be zero
没有改动程序，训练时出现了这样的错误

**Comment by wzy0022** [comment]
I have encountered the same problem, how did you solve it
